//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by testocx.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTOCX_DIALOG              102
#define IDS_PROPSHT_CAPTION             103
#define IDD_PROPPAGE1                   104
#define IDD_DNCINFO                     104
#define IDD_PROPPAGE2                   105
#define IDD_MACHINE_CONSTANTS           105
#define IDD_PROPPAGE3                   106
#define IDD_FILE_TIME                   106
#define IDD_PROPPAGE0                   107
#define IDD_CONNECT                     107
#define IDD_PROPPAGE4                   108
#define IDD_PRESET                      108
#define IDD_PROPPAGE5                   109
#define IDD_FILE_TRANSFER               109
#define IDD_TABLE                       110
#define IDD_PLC_COMMUNICATION           111
#define IDD_MESSAGE                     112
#define IDD_EVENTS                      113
#define IDD_DNC                         114
#define IDD_BACKUP                      115
#define IDR_MAINFRAME                   128
#define IDC_CONNECT                     1001
#define IDC_FILENAME                    1002
#define IDC_RECONNECT                   1002
#define IDC_COMMAND                     1003
#define IDC_SQLSTRING                   1003
#define IDC_START                       1004
#define IDC_STARTLINE                   1004
#define IDC_TIME                        1004
#define IDC_ABORT                       1005
#define IDC_BASE_ROT                    1005
#define IDC_LSV2                        1006
#define IDC_TABLE_ENTRY                 1006
#define IDC_ADDRESS                     1007
#define IDC_FCLEAR                      1008
#define IDC_FADD                        1009
#define IDC_CLASS                       1010
#define IDC_EVID                        1012
#define IDC_EVENTS                      1013
#define IDC_EVNAME                      1014
#define IDC_PRIORITY                    1015
#define IDC_SENDER                      1016
#define IDC_APPLY                       1017
#define IDC_FIRST                       1019
#define IDC_SET_TIME                    1019
#define IDC_TABLELINE                   1021
#define IDC_CHAT_ADD                    1022
#define IDC_CHAT_CLEAR                  1023
#define IDC_CHAT_CLOSE                  1024
#define IDC_CHAT_LINE                   1025
#define IDC_LEFT                        1026
#define IDC_TOP                         1027
#define IDC_ROWS                        1028
#define IDC_COLUMNS                     1029
#define IDC_CHAT_OPEN                   1030
#define IDC_CHAT_FONT                   1031
#define IDC_BTN_STATUS                  1032
#define IDC_STATUS                      1033
#define IDC_INFO                        1033
#define IDC_CONVERTER                   1034
#define IDC_VERSION                     1034
#define IDC_CONVERTERPATH               1035
#define IDC_LBL_PARA                    1037
#define IDC_PARAMETER                   1038
#define IDC_CONSTANT_NAMES              1039
#define IDC_CONSTANT_VALUES             1040
#define IDC_SET_CONSTANT                1041
#define IDC_EXECUTION_MODE              1042
#define IDC_GET_CONSTANT                1043
#define IDC_MC                          1045
#define IDC_IMMEDIATE2                  1046
#define IDC_IMMEDIATE                   1047
#define IDC_WC                          1048
#define IDC_SET_PRESET                  1049
#define IDC_CURRENT_TIME                1050
#define IDC_SPECIFIC_TIME               1051
#define IDC_PROTOCOL_FILE               1052
#define IDC_TRANSMIT_AUTO               1053
#define IDC_BIN_TYPES                   1054
#define IDC_NC_NAME                     1055
#define IDC_PC_NAME                     1056
#define IDC_RECEIVE_AUTO                1057
#define IDC_CONNECTIONCONTROL           1057
#define IDC_PLC_STRING                  1058
#define IDC_PROGRESSDLG                 1058
#define IDC_PLC_DWORD                   1059
#define IDC_MODETEXT                    1059
#define IDC_MODEBIN                     1060
#define IDC_SCAN                        1060
#define IDC_MODEAUTO                    1061
#define IDC_BACKUP                      1061
#define IDC_BACKGROUNDTRANSFER          1062
#define IDC_RESTORE                     1062
#define IDC_RECEIVED_STRING             1063
#define IDC_OVERWRITE                   1063
#define IDC_BCKFILE                     1063
#define IDC_TRANSMIT                    1064
#define IDC_MODEMERGE                   1064
#define IDC_LSTFILE                     1064
#define IDC_TRANSMIT_STRING             1065
#define IDC_SCAN_MODE                   1065
#define IDC_SCAN_MODE2                  1066
#define IDC_TEST                        1066
#define IDC_RECEIVED_DWORD              1067
#define IDC_SCAN_MODE3                  1067
#define IDC_LANGUAGE                    1067
#define IDC_CLEAR                       1068
#define IDC_SCAN_MODE4                  1068
#define IDC_SCANFOLDER                  1069
#define IDC_BCKLSTFILE                  1070

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
